# Generated by Django 5.0.14 on 2026-06-10 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCanal',
            fields=[
                ('id_canal', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_canal', models.CharField(max_length=50)),
                ('sub_canal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DimCliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('segmento', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DimProducto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('precio_base', models.IntegerField()),
                ('proveedor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FactVentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venta', models.IntegerField()),
                ('id_fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('precio_final', models.IntegerField()),
                ('importe_total', models.IntegerField()),
                ('utilidad', models.IntegerField()),
                ('tienda_local', models.CharField(max_length=100)),
                ('id_canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.dimcanal')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.dimcliente')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.dimproducto')),
            ],
            options={
                'db_table': 'Fact_Ventas',
                'unique_together': {('id_venta', 'id_producto')},
            },
        ),
    ]
